### ISSUE TITLE
`realip cloudflare` is unclear

### ISSUE THREAD

**Issue by jleclanche** [captncraig/caddy-realip#8]
It's unclear what `realip cloudflare` does until we look at the actual code: It simply adds the cloudflare IPs as the `from`.

However, it doesn't look like it's possible to do something like this:

```
realip cloudflare {
    header CF-Connecting-IP
    strict
}
```

Or this:

```
realip {
    header CF-Connecting-IP
    from cloudflare
    from 1.2.3.4/32
}
```

The latter would be the ideal syntax to support I think.

**Comment by captncraig** [comment]
Both good points. Does cloudflare set both X-Forwarded-For and CF-Connecting-IP? What is the difference?

I'd be ok with your first example. It just requires removing a check [here](https://github.com/captncraig/caddy-realip/blob/master/setup.go#L56) to allow further customization.

**Comment by jleclanche** [comment]
It does. CF-Connecting-IP i believe is always the original IP, whereas X-Forwarded-For is multipass.

The reason I prefer the second syntax is because you'd be treating `cloudflare` as kind of an alias to a bunch of IPs at once without touching the rest of the syntax.

**Comment by captncraig** [comment]
I definitely agree when I look at it that way, but I don't want to break anybody using the first way either. Supporting both ways feels odd, but may work.

**Comment by captncraig** [comment]
The preset could also set the Header field potentially as well

**Comment by jleclanche** [comment]
Could support both for 1-2 releases and deprecate it?

**Comment by captncraig** [comment]
#9 should address this.
